In [14]:
from sklearn import datasets  
from sklearn.model_selection import train_test_split  
from sklearn import svm  
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score  
import pandas as pd
import numpy as np

In [24]:
df=pd.read_csv('人口.csv',encoding='gbk')
X=df.filter(regex='[^自然增长率(%)]')[:-1]
y=np.array(df['自然增长率(%)'][1:])#明年自然增长率
scaler = StandardScaler()  



In [29]:
name=df.columns
df_scaler=scaler.fit_transform(df)
name,
X_scaled = df_scaler[:,:-1]
X_scaled

array([[-1.69774938,  2.31231635, -1.98778923, -0.67360782,  0.28065341,
        -1.72963591, -1.15697989,  1.16218409, -1.07953007],
       [-1.62845348,  1.83270783, -1.85787421, -0.67193038,  0.18148259,
        -1.65933538, -1.16554757,  1.17076574, -1.1556617 ],
       [-1.55915759,  1.82969143, -1.74474303, -0.66756903,  0.13189719,
        -1.63775415, -1.17482923,  1.18006252, -1.16630838],
       [-1.4898617 ,  1.51900163, -1.62661735, -0.65884632,  0.231068  ,
        -1.58619182, -1.16983142,  1.17505656, -1.25238214],
       [-1.4205658 ,  0.85237595, -1.53090883, -0.65783985,  0.25586071,
        -1.53986326, -1.17268731,  1.17791711, -1.32303386],
       [-1.35126991,  0.47834163, -1.44025289, -0.65180105,  0.45420234,
        -1.48823631, -1.15983579,  1.16504464, -1.2734798 ],
       [-1.28197402, -0.28480903, -1.36492889, -0.65616241,  0.59056221,
        -1.44520308, -1.15269605,  1.15717813, -1.30714211],
       [-1.21267813, -0.48389182, -1.27740903, -0.64945263,  0

In [17]:

X_scaled = scaler.fit_transform(X) 

#X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
train=[i for i in range(40)]
test=[i for i in range(40,49)]
X_train, X_test, y_train, y_test=X_scaled[train],X_scaled[test],y[train],y[test]


In [18]:
X_scaled[:,0]
df_sc=scaler.fit_transform(df)
df_sc[:,5]

array([-1.72963591, -1.65933538, -1.63775415, -1.58619182, -1.53986326,
       -1.48823631, -1.44520308, -1.41011743, -1.36004123, -1.30369742,
       -1.2173079 , -1.12917378, -1.02772909, -0.95400399, -0.84021794,
       -0.73192411, -0.64088235, -0.54389605, -0.44367903, -0.37938765,
        0.22928052,  0.27722444,  0.3199346 ,  0.36232168,  0.40412723,
        0.44354205,  0.50072584,  0.55694042,  0.60326898,  0.65864357,
        0.70329216,  0.74929765,  0.78050643,  0.80997062,  0.84408705,
        0.86237294,  0.89022177,  0.91238453,  0.92808584,  0.94514406,
        0.96304226,  0.98339582,  1.00174632,  1.01938607,  1.03721966,
        1.05001332,  1.05983472,  1.06222545,  1.05873627,  1.05130561])

In [19]:
# 初始化SVM回归模型  
svr = svm.SVR(kernel='linear') # 这里使用了线性核函数  

# 训练模型  
svr.fit(X_train, y_train)  



SVR(kernel='linear')

In [20]:
# 对测试集进行预测  
y_pred = svr.predict(X_test)  

# 计算均方误差（MSE）  
mse = mean_squared_error(y_test, y_pred)  
print('Mean Squared Error:', mse)  
y_pred

Mean Squared Error: 0.5333333177411517


array([4.62017402, 4.45015723, 4.56414125, 4.42103226, 4.59397439,
       4.21120276, 5.09116803, 4.44190945, 2.65587285])

In [21]:
wight=svr.coef_
name=X.columns
wight,name

(array([[-0.49129428,  2.47750119, -0.95101508, -0.53472542, -0.05419678,
         -0.95450943,  0.20455729, -0.12500269, -0.27580167]]),
 Index(['年份', '出生人口(万)', '总人口(万人)', '中国人均GPA(美元计)', '中国性别比例(按照女生=100)',
        '中国就业人口(万人)', '城镇人口(城镇+乡村=100)', '乡村人口', '美元兑换人民币汇率'],
       dtype='object'))

In [22]:
'''
from pyecharts.charts import Bar
from pyecharts import options as opts
wight2=[round(i,2) for i in wight[0]]
bar = Bar()
bar.add_xaxis(list(name))
bar.add_yaxis("权重",wight2)
bar.set_global_opts(title_opts=opts.TitleOpts(title="权重图"))
#bar.render()
bar.render("权重图.html")'''

ImportError: cannot import name 'Bar' from 'pyecharts.charts' (D:\Users\86130\anaconda3\lib\site-packages\pyecharts\charts\__init__.py)

In [ ]:
'''bar = Bar()
y_pred2=[round(i,2) for i in y_pred]
bar.add_xaxis([2011,2012,2013,2014,2015,2016,2017,2018,2019])
bar.add_yaxis("预测增长率", list(y_pred2))
bar.add_yaxis("真实测增长率", list(y_test))
bar.set_global_opts(title_opts=opts.TitleOpts(title="增长率预测图"))
#bar.render()
bar.render("预测图.html")'''


'd:\\Users\\86130\\Desktop\\千峰py实习\\py_obj\\预测图.html'

In [ ]:
y_test

array([4.79, 4.95, 4.92, 5.21, 4.96, 5.86, 5.32, 3.81, 3.34])